apiVersion: v1
kind: Service
metadata:
  name: ENV_APP_NAME 
  namespace: ENV_CUSTOMER-ENV_NAMESPACE
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ENV_APP_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ENV_APP_NAME 
  namespace: ENV_CUSTOMER-ENV_NAMESPACE
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: ENV_APP_NAME
  template:
    metadata:
      labels:
        app: ENV_APP_NAME
    spec:
      containers:
        - name: ENV_APP_NAME
          image: CONTAINER_IMAGE@IMAGESHA
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080

